version: '3'

services:
    nginx:
        build:
            context: ./docker/nginx
        container_name: ubtracker_nginx
        volumes:
            - ./public:${APP_PATH}/public
        working_dir:    ${APP_PATH}/public
        ports:
            - ${NGINX_PORT}:80
        links:
            - php-fpm
        depends_on:
            - php-fpm

    mysql:
        image:          mysql:8
        container_name: ubtracker_mysql
        volumes:
            - ./docker/data/db:/var/lib/mysql
        command:
            - "--default-authentication-plugin=mysql_native_password"
            - "--lower_case_table_names=1"


    mongo:
        image:          mongo:4.2-bionic
        container_name: ubtracker_mongo
        volumes:
            - ./docker/data/mongo:/data/db

    php-fpm:
        build:
            context:    .
            dockerfile: ./docker/php-fpm/Dockerfile
            args:
                XDEBUG_REMOTE_PORT:     ${XDEBUG_REMOTE_PORT}
                APP_PATH:               ${APP_PATH}
                APP_ENV:                ${APP_ENV}
        container_name: ubtracker_php
        working_dir:    /usr/share/nginx/ubtracker
        links:
            - mysql
            - mongo
        volumes:
            - ./bin:${APP_PATH}/bin
            - ./config:${APP_PATH}/config
            - ./public:${APP_PATH}/public
            - ./src:${APP_PATH}/src
            - ./vendor:${APP_PATH}/vendor:rw
            - ./composer.json:${APP_PATH}/composer.json
            - ./composer.lock:${APP_PATH}/composer.lock
            - ./symfony.lock:${APP_PATH}/symfony.lock
